# Generated by Django 4.2.4 on 2023-12-08 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0004_blog_description_blog_image_1_blog_image_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_price',
            field=models.DecimalField(decimal_places=0, max_digits=9, null=True),
        ),
    ]
