# Generated by Django 4.2.4 on 2023-12-08 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0006_alter_blog_description_alter_blog_image_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='content1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='content2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='content3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='modified_timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
