# Generated by Django 4.2.4 on 2023-12-08 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0007_blog_content1_blog_content2_blog_content3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='meta_description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
